@startuml
set separator none
skinparam classAttributeIconSize 0
hide circle

class polygon {
    +MAZ_SIDES: int<<final>>
    -numSides:int
    -points:Point[]
    + addPoint(point : Point) : void
    + addPoint(point : Point) : void
    + perimeter() : double
    + toString() : String <<override>>
    - lineLength(p1 : Point, p2 : Point) : double
}
